version: "3.9"

services:
  web:
    image: backend
    build:
      context: ./app
      dockerfile: Dockerfile
    platform: linux/amd64
    restart: always
    depends_on:
      - db
    ports:
      - "5001:5001"
    volumes:
      - ./app:/app   #allow on the fly edit

  db:
    # image: mysql/mysql-server:8.0.23
    image: mariadb:latest
    container_name: mariadb
    restart: on-failure
    ports:
      - "33000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: meteor
      MYSQL_USER: root
    volumes:
      # - ./db:/docker-entrypoint-initdb.d/:ro
      - meteorData:/var/lib/mysql

   
  # db_test:
  #   #testing database
  #   image: mariadb:latest
  #   container_name: mariadb-test
  #   restart: on-failure
  #   ports:
  #     - "33001:3307"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: meteor
  #     MYSQL_USER: root
  #   volumes:
  #     - ./db:/docker-entrypoint-initdb.d/:ro

volumes:
  meteorData: 
